### ISSUE TITLE
Choppy scrolling (jank) in Chrome 41, Not working at all in Safari 6.0.2

### ISSUE THREAD

**Issue by Natedude** [flesler/jquery.scrollTo#108]
Firefox is working great though...
Here is a Codepen where the problem is occurring. http://codepen.io/Solvoid/full/jEvQqw/

**Comment by flesler** [comment]
Hi, the choppiness is likely due to the 1.5Mb image. This plugin is using jQuery's animate() function without any fanciness, so you're likely to see it like that even if you use jQuery by itself.

In fact, it's super slow even when I scroll manually from the scrollbar, you'll need to optimize the content.

About Safari, could it be related to #9?
You can try the [unreleased beta version](https://github.com/flesler/jquery.scrollTo/blob/window-scroll-alt/jquery.scrollTo.js) and see if the issue with Safari is solved.
