### ISSUE TITLE
scroll event fires after onAfter

### ISSUE THREAD

**Issue by SlightlyCyborg** [flesler/jquery.scrollTo#111]
If I scroll to an item and put a .selected on it in the onAfter function and then also bind a scroll event handler to remove all .selected what should happen is that scrollTo will scroll to the element, remove all .selected classes and then put .selected on the item scrolled to. What ends up happening is that the scroll event fires AFTER the onAfter thereby removing .selected that was just set on the item.

**Comment by flesler** [comment]
I just tested that on the plugin's demo and the onAfter console.log showed after all the ones coming from the window scroll handler.

Not sure if it's a browser thing (I tested on FF Win) or something to do with your implementation.
Can you create a jsfiddle or similar that reproduces this? you can use console.log instead of altering CSS classes, it's easier to follow.

BTW, there probably are better ways to delesect that doing that on the scroll handler which is called VERY frequently (64 per second on my browser). Still this is obviously unrelated to the main problem.

**Comment by brewster1134** [comment]
i am seeing this as well...

```coffee
$(window).on 'scroll', =>
  if @enableScrollEvent
    console.log 'scroll event'

@enableScrollEvent = false

$.scrollTo 100,
  onAfter: =>
    @enableScrollEvent = true
```

this unexpectedly logs `scroll event`

**Comment by flesler** [comment]
Not sure guys, maybe the scroll event occurs sort of "on next frame" so it's delayed, the onAfter is set on jQuery's complete callback, it's supposed to be after.
I'll dive on this once I get a while, if you find out something please share

**Comment by brewster1134** [comment]
it seems to work as expected if you use `requestAnimationFrame`.  if that turns out to be an actual fix, and you decide to integrate it into the scrollTo source, its worth mentioning the [browser support](http://caniuse.com/#feat=requestanimationframe).  personally i like the idea of integrating it and documenting that if you use onAfter, you may need to load a polyfill.

```coffee
$(window).on 'scroll', =>
  if @enableScrollEvent
    console.log 'scroll event'
  else
    console.log 'no scroll event'

@enableScrollEvent = false

$.scrollTo 100,
  onAfter: =>
    requestAnimationFrame =>
      @enableScrollEvent = true
```

**Comment by flesler** [comment]
It's personal taste, but I wouldn't add that it's not something that troubles too many users so it doesn't justify requiring a polyfill or re-implementing one in the plugin.
I'm not sure what else to do about this issue

**Comment by brewster1134** [comment]
you could check for `requestAnimationFrame` support and use it if its supported. that way you wouldnt NEED a polyfill.  the only reason i like adding support for it into scrollTo, is because scrollTo is an animation based library.  not only for the callback, but for when it engages jquery's `animate()`, you may seem an improvement in performance. 

but yea... it really just comes down to deciding one way or another. i definetely think its worth mentioning in the docs though :wink:

**Comment by dwelle** [comment]
This cost me some 2-3 hrs of debugging of a fairly complex piece of code, because I didn't expect this would be happening, until it was fairly obvious this must be the case, which it was. 

@brewster1134 thanks for the hack, which is somewhat better than `setTimeout` I was trying.

**Comment by vinnymac** [comment]
@flesler I ran into this issue as well a long time ago, in an old project. I don't think you should polyfill, or fix the issue. I debugged and realized I should be using requestAnimationFrame fairly quickly, as others should. The only thing I recommend is adding a note about using it in the documentation, maybe with an example or a recommended polyfill to use.

**Comment by flesler** [comment]
Hi @vinnymac, thanks for the input.
Do you have a text in mind? Would you make a PR?
