### ISSUE TITLE
Functionality to scroll elements to center around another element

### ISSUE THREAD

**Issue by denizdogan** [flesler/jquery.scrollTo#132]
It would be a really nice feature to have, as the necessary calculations are often tricky to implement on your own.

Example usage:

```javascript
$(scrollableElem).scrollTo(targetElem, {center: "x"});
```

Valid values for the `center` option could be e.g. `x`, `y`, `xy` or `true` (which could be the same as xy)

**Comment by flesler** [comment]
Hi, I think this is already achievable with the settings provided, something like:
```js
$(scrollableElem).scrollTo(targetElem, {
  axis:'y', over:0.5,
  offset: -$(window).height() / 2
});
```

If the container is not the window, you'll need to use the scrollHeight of the container instead of $(window),height(). Same code can be tweaked for horizontal scrolling easily.

The math might be slightly wrong, if you see it scroll to the wrong position try playing with it a bit.

**Comment by denizdogan** [comment]
@flesler: That seems to do the trick, I verified it [using this Plnkr](http://plnkr.co/edit/7O1pMDIGUXjhwW81Rbom?p=preview), thanks. At first it seemed like it was off by a few pixels, but that was just because of the scrollbars. I still think it would be a nice to have feature though!

**Comment by flesler** [comment]
I aim to make the settings versatile so users have a way to achieve this kind of ad-hoc needs without me implementing every use case, I'll close

**Comment by brunoinds** [comment]
With you wanna center to middle of "x" axis (as a carousel), use this code:

```
$(parent).scrollTo(elementToBeCentered, 300, {
   over: 0.5,
   axis: 'x',
   offset: -$(parent).width() / 2
});
```
