### ISSUE TITLE
Second scrollTo on I phone IOS 9.3.2

### ISSUE THREAD

**Issue by shadowroot2** [flesler/jquery.scrollTo#135]
At first scrollTo works, when next run scrollTo do nothnik on other devices is ok

**Comment by flesler** [comment]
Hi, you need to provide a lot more information to be able to reproduce the issue.

First, try to reproduce it on the plugin's [demo page](http://demos.flesler.com/jquery/scrollTo/). If it works there, you'll need to debug your code because the problem is likely there.

If you can, please report the steps to reproduce.
Thanks
