### ISSUE TITLE
[bower] name should be lowercase

### ISSUE THREAD

**Issue by DanielRuf** [flesler/jquery.scrollTo#165]
`jquery.scrollTo` should be `jquery.scrollto`

**Comment by flesler** [comment]
I've been doing some reading and testing, it seems like [I shouldn't](https://github.com/bower/bower/issues/1751#issuecomment-241660771). Tried locally and indeed, while they recommend lowercase, the name is case sensitive. If I rename it will break for everyone currently using it.

Currently the only real problem is you get a warning, it's not too bad. I tried registering the lowercase version against the same git repo and it's working. Using `bower install jquery.scrollto` I didn't get the lowercase warning so, the current state could be a good middle ground.

What do you think?

**Comment by DanielRuf** [comment]
Ok so updating the readme to use `scrollto` instead of `scrollTo` would be a working solution?

Anyway, bower is dead and npm is the new way. I'll check if there are also issues with the npm package.

**Comment by flesler** [comment]
In theory yes, but I'm not sure and lacking the time to do deep testing.
I think we should just leave it as it is. As you said, bower is dead and this now works with both cases
