### ISSUE TITLE
Update core animate() to allow additional functionality

### ISSUE THREAD

**Issue by peterh-capella** [flesler/jquery.scrollTo#35]
At its heart, jquery.scrollTo uses this format of the `.animate()` method:

    .animate(properties [, duration ] [, easing ] [, complete ])

Would it be possible to use the alternate version of the `.animate()` method:

    .animate(properties, options)

to allow optional passing in of additional properties that could be animated while the scroll is happening? For example, animating (with the proper plug-ins) the background color of an element while it scrolls.

It appears on cursory examination that this would involve moving the current `duration`, `settings.easing`, and `callback` arguments to a new `options` object as well as getting the current `attr` argument into a new `properties` object along with any other properties that are passed into the plug-in.

**Comment by flesler** [comment]
This feature is implemented on the [window-scroll-alt](https://github.com/flesler/jquery.scrollTo/tree/window-scroll-alt) branch. I created the issue #107 for the whole thing that has a larger scope.
If that branch makes it to master this issue will be fixed too.

**Comment by flesler** [comment]
I merged 2.0.0 to master via #109, the call to `$().animate()` receives the whole setting object so any setting supported by your version of [$().animate()](http://api.jquery.com/animate/) can also be used with scrollTo.
If you have any issue after the update, first check [this link](https://github.com/flesler/jquery.scrollTo/wiki/Migrating-to-2.0), If your problem is not solved then go ahead and [report the issue](https://github.com/flesler/jquery.scrollTo/issues/new).
