### ISSUE TITLE
Flickering on iOS 7 Emulator and Real Devices

### ISSUE THREAD

**Issue by robertegnacheski** [flesler/jquery.scrollTo#63]
Getting a flicker on iOS7. Tried the return false as some have suggested, but still running into issues with flickering.

Here is the code I am trying-

$('.navbar-brand').click(function(evt){ evt.preventDefault(); $(window).scrollTo( 0, 500, {offset:0} ); return false;});

**Comment by flesler** [comment]
This might get fixed with #107. I'm not sure why this happens, one guess is that maybe the scrollLeft is also being animated (to the same value) all the time and causes the flicker.
If that is indeed the reason, #107 is likely to fix it because the scroll is not re-set if the value hasn't changed.

**Comment by flesler** [comment]
I merged 2.0.0 to master via #109 and this issue might be now fixed.
If you have any issue after the update, first check [this link](https://github.com/flesler/jquery.scrollTo/wiki/Migrating-to-2.0), If your problem is not solved then go ahead and [report the issue](https://github.com/flesler/jquery.scrollTo/issues/new).

If you are not scrolling horizontally, please also try this:
```js
$.scrollTo.defaults.axis = 'y';
```

**Comment by aleixfabra** [comment]
I added:
```javascript
$.scrollTo.defaults.axis = 'y';
```
as @flesler said and it's working to me now!

**Comment by flesler** [comment]
Great, anyone, feel free to reopen if still happens with the default axis change
