### ISSUE TITLE
horizontal scrolling not working in safari 6?

### ISSUE THREAD

**Issue by onedrop** [flesler/jquery.scrollTo#9]
Having an issue in safari 6 on os x mountain lion. For example, when trying to issue a scrollTo() command in a 2000/2000px html body, only the vertical component is scrolled. Is anyone else experiencing this? It works find in safari 5, ie9, firefox and chrome.

$.scrollTo({left:1000, top:1000}, 1000);

**Comment by flesler** [comment]
Hi,

On #101 we're testing a new beta version (currently 1.5.2-beta) that fixes scrolling in Chrome 40 (was working on most ends but not all), also works correctly on iOS and Android which wasn't previously working. I tested this version with my Safari 8.0 and it works.

I'd like you to join us on that other issue and run the [tests](http://flesler.github.io/jquery.scrollTo/tests/) on your available browsers (including Safari 6), I won't be releasing this until it gets enough confirmation from users.

Thank you

**Comment by klihelp** [comment]
The new version looks good

**Comment by flesler** [comment]
You tested it on Safari 6?

**Comment by flesler** [comment]
I merged 2.0.0 to master via #109 and this issue might get fixed (indirectly).
If the problem persists please reopen the issue with details on the situation.
If you have any issue after the update, first check [this link](https://github.com/flesler/jquery.scrollTo/wiki/Migrating-to-2.0), If your problem is not solved then go ahead and [report the issue](https://github.com/flesler/jquery.scrollTo/issues/new).
